// MIT License
// Copyright (c) 2017 nessie1980 (nessie1980@gmx.de)
#include "PresenterSaleEdit.h"
#include "../../utils/DocumentClassifier.h"

#include <QTimer>
#include <QUuid>
#include <QDateTime>

// ── Constructor ───────────────────────────────────────────────────────────────

PresenterSaleEdit::PresenterSaleEdit(IViewSaleEdit*   view,
                                     IModelSaleEdit*  model,
                                     const QString&   shareGuid,
                                     DocumentsConfig* config,
                                     QObject*         parent)
    : QObject(parent)
    , m_view(view)
    , m_model(model)
    , m_config(config)
    , m_shareGuid(shareGuid)
{
    connect(&m_parser, &ParserLib::Parser::parserUpdated,
            this,      &PresenterSaleEdit::onParserUpdated);
    connect(&m_pdfExtractor, &PdfTextExtractor::finished,
            this,            &PresenterSaleEdit::onPdfTextExtracted);

    // Populate available buys (no depot filter yet — depot not selected)
    m_view->populateAvailableBuys(m_model->loadAvailableBuys(shareGuid));
    // All buys (incl. fully sold) for document lookup in the Details dialog
    m_view->setAllBuys(m_model->loadAllBuys(shareGuid));
    // Splits der Aktie — einmalig, siehe IViewSaleEdit::setSplits() (Phase 2c
    // der Aktiensplit-Behandlung, 07.08.2026, ARCHITECTURE.md "Offene Punkte").
    m_view->setSplits(m_model->loadSplits(shareGuid));

    reloadOverview();
    m_view->clearForm();
    m_view->setButtonStates(/*canRemove=*/false, /*isLastSale=*/false, /*isEdit=*/false);
}

// ── onSave ────────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onSave()
{
    const QString error = validateInput();
    if (!error.isEmpty()) {
        m_view->showError(error);
        return;
    }

    const bool isEdit = !m_currentSaleGuid.isEmpty();

    // Non-latest sale: only the document path may change
    if (isEdit && !m_isLastSale) {
        for (SaleObject& s : m_sales) {
            if (s.guid() == m_currentSaleGuid) {
                s.setDocument(m_view->documentPath().trimmed());
                if (!m_model->updateSale(s)) {
                    m_view->showError(m_model->lastError());
                    return;
                }
                emit dataChanged();
                reloadOverview();
                m_currentSaleGuid.clear();
                m_isLastSale = false;
                m_view->setButtonStates(false, false, false);
                m_view->showOverviewTab();
                return;
            }
        }
        return;
    }

    // New sale or latest-sale full edit
    const QString guid = isEdit
        ? m_currentSaleGuid
        : QUuid::createUuid().toString(QUuid::WithoutBraces);

    // FIFO-Zuteilung immer frisch berechnen — sowohl für neue Verkäufe als
    // auch beim vollständigen Bearbeiten des jüngsten Verkaufs (07.08.2026,
    // Nessies Entscheidung: die vorherige Fassung übernahm beim Bearbeiten
    // unverändert die gespeicherten SaleBuyDetails, auch wenn sich die
    // Verkaufsmenge im Formular geändert hatte — siehe ARCHITECTURE.md,
    // "Offene Punkte", "Aktiensplits werden nicht behandelt", Phase 2c).
    // An dieser Stelle ist isEdit nur dann true, wenn zugleich m_isLastSale
    // gilt — der nicht-jüngste Zweig oben hat bereits per return verlassen.
    //
    // Beim Bearbeiten müssen die vom BISHERIGEN Verkauf beanspruchten
    // Anteile zunächst virtuell zurückgebucht werden: buy.volumeSold() in
    // der DB spiegelt bis zum tatsächlichen Speichern noch den alten
    // Verkauf wider, siehe loadAvailableBuysForDepotExcludingSale().
    const QList<BuyObject> available = isEdit
        ? m_model->loadAvailableBuysForDepotExcludingSale(
              m_shareGuid, m_view->depotNumber(), m_currentSaleGuid)
        : m_model->loadAvailableBuysForDepot(m_shareGuid, m_view->depotNumber());

    const QDate saleDate = QDateTime::fromString(m_view->dateTime(), Qt::ISODate).date();
    const QList<ShareSplitObject> splits = m_model->loadSplits(m_shareGuid);

    QList<SaleBuyDetail> buyDetails;
    for (const FifoAllocationRow& row :
         SaleFifoAllocator::allocate(m_view->volume(), saleDate, available, splits)) {
        buyDetails.append(SaleBuyDetail(row.buyGuid, row.buyDateTime,
                                        row.volume, row.buyPrice));
    }

    const SaleObject sale(
        guid,
        m_shareGuid,
        m_view->depotNumber().trimmed(),
        m_view->orderNumber().trimmed(),
        m_view->dateTime(),
        m_view->volume(),
        m_view->salePrice(),
        buyDetails,
        m_view->taxAtSource(),
        m_view->capitalGainsTax(),
        m_view->solidarityTax(),
        QString(),   // brokerageGuid — generated by model
        m_view->provision(),
        m_view->brokerFee(),
        m_view->traderFee(),
        m_view->reduction(),
        m_view->documentPath().trimmed());

    const bool ok = isEdit
        ? m_model->updateSale(sale)
        : m_model->addSale(sale);

    if (!ok) { m_view->showError(m_model->lastError()); return; }

    emit dataChanged();
    reloadOverview();

    m_currentSaleGuid.clear();
    m_isLastSale = false;
    m_view->setButtonStates(false, false, false);
    m_view->showOverviewTab();
}

// ── onRemove ──────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onRemove()
{
    if (m_currentSaleGuid.isEmpty()) return;

    if (!m_isLastSale) {
        m_view->showError(tr("Dieser Verkauf kann nicht entfernt werden.\n"
                              "Es darf nur der jüngste Verkauf gelöscht werden."));
        return;
    }

    if (!m_model->removeSale(m_currentSaleGuid)) {
        m_view->showError(m_model->lastError());
        return;
    }

    emit dataChanged();
    m_currentSaleGuid.clear();
    m_isLastSale = false;
    reloadOverview();
    m_view->setButtonStates(false, false, false);
    m_view->showOverviewTab();
}

// ── onReset ───────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onReset()
{
    m_currentSaleGuid.clear();
    m_isLastSale = false;
    m_view->setButtonStates(false, false, false);
    // Clear depot filter — show all available buys again
    m_view->populateAvailableBuys(m_model->loadAvailableBuys(m_shareGuid));
    refreshDerivedValues();
    m_view->showOverviewTab();
}

// ── onClose ───────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onClose()
{
    m_view->acceptAndClose();
}

// ── onRowSelected ─────────────────────────────────────────────────────────────

void PresenterSaleEdit::onRowSelected(const QString& saleGuid)
{
    if (saleGuid.isEmpty()) { onReset(); return; }

    for (const SaleObject& s : std::as_const(m_sales)) {
        if (s.guid() == saleGuid) {
            m_currentSaleGuid = saleGuid;
            m_isLastSale = isLatestSale(saleGuid);
            const bool canRemove = m_isLastSale;
            m_view->loadSale(s);
            // Refresh available buys for this sale's depot — mit
            // zurückgebuchten eigenen Anteilen, siehe
            // loadAvailableBuysForDepotExcludingSale() (Phase 2c). Für einen
            // nicht-jüngsten Verkauf bleibt das Ergebnis ungenutzt (die
            // Details-Vorschau zeigt dort die gespeicherte Zuteilung), daher
            // hier bewusst unbedingt aufgerufen statt nach isLastSale
            // verzweigt.
            m_view->populateAvailableBuys(
                m_model->loadAvailableBuysForDepotExcludingSale(
                    m_shareGuid, s.depotNumber(), saleGuid));
            if (!s.document().isEmpty())
                m_view->openPdfPreview(s.document());
            else
                m_view->clearPdfPreview();
            m_view->setButtonStates(canRemove, m_isLastSale, /*isEdit=*/true);
            refreshDerivedValues();

            // Validate all fields so icons reflect the loaded state.
            onDateEdited();
            onDepotNumberEdited();
            onOrderNumberEdited();
            onVolumeOrPriceEdited();
            onFeeEdited(QStringLiteral("provision"),       m_view->provision());
            onFeeEdited(QStringLiteral("brokerFee"),       m_view->brokerFee());
            onFeeEdited(QStringLiteral("traderFee"),       m_view->traderFee());
            onFeeEdited(QStringLiteral("reduction"),       m_view->reduction());
            onTaxEdited(QStringLiteral("taxAtSource"),     m_view->taxAtSource());
            onTaxEdited(QStringLiteral("capitalGainsTax"), m_view->capitalGainsTax());
            onTaxEdited(QStringLiteral("solidarityTax"),   m_view->solidarityTax());
            onDocumentPathEdited();
            return;
        }
    }
}

// ── onValuesChanged ───────────────────────────────────────────────────────────

void PresenterSaleEdit::onValuesChanged()
{
    refreshDerivedValues();
}

// ── Live field validation ─────────────────────────────────────────────────────

void PresenterSaleEdit::onDateEdited()
{
    const QDate d = QDate::fromString(
        m_view->dateTime().left(10), Qt::ISODate);
    if (d.isValid() && d > QDate(2000, 1, 1))
        m_view->setFieldOk(QStringLiteral("date"), QString());
    else
        m_view->setFieldError(QStringLiteral("date"));
}

void PresenterSaleEdit::onDepotNumberEdited()
{
    if (!m_view->depotNumber().trimmed().isEmpty()) {
        m_view->setFieldOk(QStringLiteral("depotNumber"), QString());
    } else {
        m_view->setFieldError(QStringLiteral("depotNumber"));
    }
    // Refresh the buy list whenever the depot selection changes so the
    // Details dialog and FIFO calculation always use the right buys.
    // Beim Bearbeiten eines Verkaufs (m_currentSaleGuid gesetzt) dessen
    // eigene, bereits gebuchte Anteile zurückbuchen — Phase 2c, siehe
    // onRowSelected() oben.
    m_view->populateAvailableBuys(
        m_currentSaleGuid.isEmpty()
            ? m_model->loadAvailableBuysForDepot(m_shareGuid, m_view->depotNumber())
            : m_model->loadAvailableBuysForDepotExcludingSale(
                  m_shareGuid, m_view->depotNumber(), m_currentSaleGuid));
    refreshDerivedValues();
}

void PresenterSaleEdit::onOrderNumberEdited()
{
    const QString nr = m_view->orderNumber().trimmed();
    if (nr.isEmpty()) {
        m_view->setFieldError(QStringLiteral("orderNumber"));
        return;
    }
    if (m_model->orderNumberExists(m_shareGuid, nr, m_currentSaleGuid))
        m_view->setFieldError(QStringLiteral("orderNumber"));
    else
        m_view->setFieldOk(QStringLiteral("orderNumber"), QString());
}

void PresenterSaleEdit::onVolumeOrPriceEdited()
{
    if (m_view->volume() > 0.0)
        m_view->setFieldOk(QStringLiteral("volume"), QString());
    else
        m_view->setFieldError(QStringLiteral("volume"));

    if (m_view->salePrice() > 0.0)
        m_view->setFieldOk(QStringLiteral("salePrice"), QString());
    else
        m_view->setFieldError(QStringLiteral("salePrice"));
}

void PresenterSaleEdit::onFeeEdited(const QString& fieldKey, double value)
{
    if (value < 0.0)
        m_view->setFieldError(fieldKey);
    else
        m_view->setFieldOk(fieldKey, QString());
}

void PresenterSaleEdit::onTaxEdited(const QString& fieldKey, double value)
{
    if (value < 0.0)
        m_view->setFieldError(fieldKey);
    else
        m_view->setFieldOk(fieldKey, QString());
}

void PresenterSaleEdit::onDocumentPathEdited()
{
    const QString path = m_view->documentPath().trimmed();
    if (path.isEmpty()) {
        m_view->setFieldOk(QStringLiteral("document"), QString());
        return;
    }
    if (m_model->documentExists(path, m_currentSaleGuid))
        m_view->setFieldError(QStringLiteral("document"));
    else
        m_view->setFieldOk(QStringLiteral("document"), QString());
}

// ── onDocumentSelected ────────────────────────────────────────────────────────

void PresenterSaleEdit::onDocumentSelected(const QString& path)
{
    if (path.isEmpty()) return;

    m_pendingPdfPath = path;
    m_view->openPdfPreview(path);

    // Non-latest sale: only document path changes, no re-parse
    const bool isNonLatestEdit = !m_currentSaleGuid.isEmpty() && !m_isLastSale;
    if (isNonLatestEdit) return;

    m_pdfExtractor.extract(path);
}

// ── onPdfTextExtracted ────────────────────────────────────────────────────────
// Replaces the former onPdfConversionFinished(int, int) QProcess slot —
// PdfTextExtractor now owns the pdftotext invocation (see ARCHITECTURE.md).

void PresenterSaleEdit::onPdfTextExtracted(bool success, const QString& text)
{
    if (!success) {
        m_view->showError(QObject::tr(
            "PDF-Konvertierung fehlgeschlagen oder kein Text extrahierbar."));
        return;
    }

    m_pdfText = text;
    startParserForText(m_pdfText);
}

// ── startParserForText ────────────────────────────────────────────────────────
// Bank-/document-type detection now delegates to DocumentClassifier
// (see ARCHITECTURE.md) — behaviour unchanged, including the fallback to
// DocumentType::Sale when the bank matched but no identifier did.

void PresenterSaleEdit::startParserForText(const QString& pdfText)
{
    if (!m_config || !m_config->isValid()) return;

    int bankIndex = -1;
    if (!DocumentClassifier::matchBankIndex(pdfText, *m_config, bankIndex)) {
        const QStringList required = {
            "date","depotNumber","orderNumber","volume","salePrice"
        };
        for (const auto& f : required) m_view->setFieldError(f);
        m_view->onParseFinished();
        return;
    }

    const BankEntry matchedBank = m_config->entries().at(bankIndex);
    const DocumentType docType = DocumentClassifier::detectDocumentType(
        pdfText, matchedBank, DocumentType::Sale);

    const DocumentEntry* docEntry =
        DocumentsConfig::findDocument(matchedBank, docType);
    if (!docEntry) {
        m_view->onParseFinished();
        return;
    }

    m_view->setUiBusy(true);
    m_view->setParseProgress(0, QObject::tr("Dokumenten-Analyse läuft..."));

    ParserLib::ParsingValues pv(pdfText,
                                docEntry->encoding.isEmpty()
                                    ? QStringLiteral("UTF-8")
                                    : docEntry->encoding,
                                docEntry->regexList);
    m_parser.setParsingValues(pv);
    m_parser.startParsing();
}

// ── onParserUpdated ───────────────────────────────────────────────────────────

void PresenterSaleEdit::onParserUpdated(const ParserLib::ParserInfoState& state)
{
    if (state.lastErrorCode == ParserLib::ParserErrorCode::SearchRunning ||
        state.lastErrorCode == ParserLib::ParserErrorCode::SearchStarted)
    {
        const QString statusText = state.lastRegexListKey.isEmpty()
            ? QObject::tr("Dokumenten-Analyse läuft...")
            : QObject::tr("Analysiere: %1").arg(state.lastRegexListKey);
        m_view->setParseProgress(state.percentage, statusText);
        return;
    }

    if (state.lastErrorCode < ParserLib::ParserErrorCode::NoError &&
        state.lastErrorCode != ParserLib::ParserErrorCode::ParsingFailed)
    {
        m_view->setParseStatusIcon(1);
        m_view->setParseProgress(0, QObject::tr("Analyse fehlgeschlagen: %1")
                                    .arg(state.exceptionMessage));
        m_view->setUiBusy(false);
        m_view->showError(QObject::tr("Parser-Fehler: %1")
                          .arg(state.exceptionMessage));
        m_view->onParseFinished();
        return;
    }

    if (state.lastErrorCode == ParserLib::ParserErrorCode::Finished ||
        state.lastErrorCode == ParserLib::ParserErrorCode::ParsingFailed)
    {
        populateFromResult(state.searchResult);
    }
}

// ── populateFromResult ────────────────────────────────────────────────────────

void PresenterSaleEdit::populateFromResult(
    const QMap<QString, QList<QString>>& result)
{
    // ── WKN / ISIN-Prüfung ────────────────────────────────────────────────
    const ShareObject share = m_model->loadShare(m_shareGuid);
    if (share.isValid()) {
        const QString parsedWkn  = result.contains(QStringLiteral("Wkn"))
            ? result[QStringLiteral("Wkn")].value(0).trimmed().toUpper()
            : QString();
        const QString parsedIsin = result.contains(QStringLiteral("Isin"))
            ? result[QStringLiteral("Isin")].value(0).trimmed().toUpper()
            : QString();

        const bool wknMatch  = !parsedWkn.isEmpty()
            && parsedWkn.compare(share.wkn().trimmed(), Qt::CaseInsensitive) == 0;
        const bool isinMatch = !parsedIsin.isEmpty()
            && parsedIsin.compare(share.isin().trimmed(), Qt::CaseInsensitive) == 0;
        const bool anyParsed = !parsedWkn.isEmpty() || !parsedIsin.isEmpty();

        if (anyParsed && !wknMatch && !isinMatch) {
            QTimer::singleShot(0, this, [this, parsedWkn, parsedIsin,
                                          shareWkn = share.wkn()]() {
                m_view->setUiBusy(false);
                m_view->setParseStatusIcon(1);
                m_view->setParseProgress(100,
                    QObject::tr("Dokument gehört nicht zu dieser Aktie"));
                m_view->showError(
                    QObject::tr(
                        "Das gewählte Dokument gehört nicht zur aktuell geöffneten Aktie.\n\n"
                        "Dokument:  WKN %1 / ISIN %2\n"
                        "Aktie:     WKN %3")
                    .arg(parsedWkn.isEmpty() ? QObject::tr("(nicht gefunden)") : parsedWkn)
                    .arg(parsedIsin.isEmpty() ? QObject::tr("(nicht gefunden)") : parsedIsin)
                    .arg(shareWkn));
            });
            m_view->onParseFinished();
            return;
        }
    }

    static const QStringList knownXmlNames = {
        "Date","Time","DepotNumber","OrderNumber",
        "Volume","Price",
        "TaxAtSource","CapitalGainsTax","SolidarityTax",
        "Provision","BrokerFee","TraderPlaceFee","Reduction"
    };
    static const QStringList requiredXmlNames = {
        "Date","DepotNumber","OrderNumber","Volume","Price"
    };

    int found = 0, requiredFound = 0;
    for (const QString& xmlName : knownXmlNames) {
        const QString viewField = xmlNameToViewField(xmlName);
        if (viewField.isEmpty()) continue;

        if (result.contains(xmlName)) {
            const QList<QString>& values = result[xmlName];
            if (!values.isEmpty() && !values.first().trimmed().isEmpty()) {
                m_view->setFieldOk(viewField, values.first().trimmed());
                ++found;
                if (requiredXmlNames.contains(xmlName)) ++requiredFound;
            }
        }
    }

    m_view->onParseFinished();

    const int reqTotal      = requiredXmlNames.size();
    const int optionalFound = found - requiredFound;
    const int optionalTotal = knownXmlNames.size() - reqTotal;

    QTimer::singleShot(0, this, [this, requiredFound, reqTotal,
                                  optionalFound, optionalTotal]() {
        m_view->setUiBusy(false);

        if (requiredFound == reqTotal) {
            m_view->setParseStatusIcon(0);
            if (optionalFound > 0)
                m_view->setParseProgress(100,
                    QObject::tr("Analyse OK — %1/%1 Pflicht, %2/%3 Optional")
                    .arg(reqTotal).arg(optionalFound).arg(optionalTotal));
            else
                m_view->setParseProgress(100,
                    QObject::tr("Analyse OK — %1/%1 Pflicht").arg(reqTotal));
        } else {
            m_view->setParseStatusIcon(1);
            m_view->setParseProgress(100,
                QObject::tr("Analyse fehlgeschlagen — %1/%2 Pflicht")
                .arg(requiredFound).arg(reqTotal));
        }
    });
}

// ── xmlNameToViewField ────────────────────────────────────────────────────────

QString PresenterSaleEdit::xmlNameToViewField(const QString& xmlName)
{
    static const QMap<QString, QString> map = {
        { QStringLiteral("Date"),           QStringLiteral("date")           },
        { QStringLiteral("Time"),           QStringLiteral("time")           },
        { QStringLiteral("DepotNumber"),    QStringLiteral("depotNumber")    },
        { QStringLiteral("OrderNumber"),    QStringLiteral("orderNumber")    },
        { QStringLiteral("Volume"),         QStringLiteral("volume")         },
        { QStringLiteral("Price"),          QStringLiteral("salePrice")      },
        { QStringLiteral("TaxAtSource"),    QStringLiteral("taxAtSource")    },
        { QStringLiteral("CapitalGainsTax"),QStringLiteral("capitalGainsTax")},
        { QStringLiteral("SolidarityTax"),  QStringLiteral("solidarityTax")  },
        { QStringLiteral("Provision"),      QStringLiteral("provision")      },
        { QStringLiteral("BrokerFee"),      QStringLiteral("brokerFee")      },
        { QStringLiteral("TraderPlaceFee"), QStringLiteral("traderFee")      },
        { QStringLiteral("Reduction"),      QStringLiteral("reduction")      },
    };
    return map.value(xmlName, QString());
}

// ── reloadOverview ────────────────────────────────────────────────────────────

void PresenterSaleEdit::reloadOverview()
{
    m_sales = m_model->loadSales(m_shareGuid);
    m_view->populateOverview(m_sales);
}

// ── refreshDerivedValues ──────────────────────────────────────────────────────

void PresenterSaleEdit::refreshDerivedValues()
{
    const double vol        = m_view->volume();
    const double price      = m_view->salePrice();
    const double prov       = m_view->provision();
    const double broker     = m_view->brokerFee();
    const double trader     = m_view->traderFee();
    const double red        = m_view->reduction();
    const double taxSrc     = m_view->taxAtSource();
    const double taxCap     = m_view->capitalGainsTax();
    const double taxSol     = m_view->solidarityTax();

    const double saleValue    = vol * price;
    const double gesGebuehren = prov + broker + trader;
    const double taxSum       = taxSrc + taxCap + taxSol;
    const double auszahlung   = saleValue - gesGebuehren + red - taxSum;

    // Kaufwert und G/V berechnen
    double kaufwert  = 0.0;
    double gewinnVerlust = 0.0;
    {
        if (!m_currentSaleGuid.isEmpty() && !m_isLastSale) {
            // Älterer, nicht editierbarer Verkauf: gespeicherte Werte aus
            // dem SaleObject anzeigen (Felder sind ohnehin gesperrt).
            for (const SaleObject& s : std::as_const(m_sales)) {
                if (s.guid() == m_currentSaleGuid) {
                    kaufwert     = s.buyValue();                      // Anzeige: ohne Kaufbrokerage
                    gewinnVerlust = s.profitLossBrokerageReduction(); // korrekte G/V inkl. aller Gebühren
                    break;
                }
            }
        } else {
            // Neuer Verkauf ODER Bearbeitung des jüngsten Verkaufs: live
            // FIFO-Vorschau, split-bewusst (Phase 2c, 07.08.2026, siehe
            // SaleFifoAllocator.h). Muss mit onSave() übereinstimmen, sonst
            // zeigt die Vorschau während der Eingabe einen anderen Wert als
            // das, was beim Speichern tatsächlich berechnet wird.
            const QDate saleDate = QDateTime::fromString(m_view->dateTime(), Qt::ISODate).date();
            const QList<ShareSplitObject> splits = m_model->loadSplits(m_shareGuid);
            const QList<BuyObject> available = m_currentSaleGuid.isEmpty()
                ? m_model->loadAvailableBuysForDepot(m_shareGuid, m_view->depotNumber())
                : m_model->loadAvailableBuysForDepotExcludingSale(
                      m_shareGuid, m_view->depotNumber(), m_currentSaleGuid);

            for (const FifoAllocationRow& row :
                 SaleFifoAllocator::allocate(vol, saleDate, available, splits)) {
                kaufwert += row.volume * row.buyPrice;
            }
            // G/V-Vorschau: Verkaufsgebühren und Steuern abziehen
            // (Kaufbrokerage ist in der Vorschau nicht verfügbar)
            gewinnVerlust = saleValue - gesGebuehren + red - kaufwert - taxSum;
        }
    }

    m_view->setSaleValue(saleValue);
    m_view->setKaufwert(kaufwert);
    m_view->setGewinnVerlust(gewinnVerlust);
    m_view->setGesGebuehren(gesGebuehren);
    m_view->setTaxSum(taxSum);
    m_view->setAuszahlung(auszahlung);
}

// ── validateInput ─────────────────────────────────────────────────────────────

QString PresenterSaleEdit::validateInput() const
{
    QStringList missingFields;
    if (m_view->hasMissingRequiredFields(missingFields)) {
        m_view->markMissingFieldsAsFailed();
        return QObject::tr(
            "Es fehlen noch Pflichtangaben.\n"
            "Die fehlenden Felder sind in der Maske rot markiert.");
    }

    if (m_model->orderNumberExists(m_shareGuid,
                                   m_view->orderNumber().trimmed(),
                                   m_currentSaleGuid)) {
        return QObject::tr("Die Auftragsnummer \"%1\" ist für diese Aktie bereits vorhanden.")
               .arg(m_view->orderNumber().trimmed());
    }

    const QString doc = m_view->documentPath().trimmed();
    if (!doc.isEmpty() && m_model->documentExists(doc, m_currentSaleGuid)) {
        return QObject::tr("Das Dokument \"%1\" ist bereits einem anderen Verkauf zugeordnet.")
               .arg(doc);
    }

    return QString();
}

// ── isLatestSale ──────────────────────────────────────────────────────────────

bool PresenterSaleEdit::isLatestSale(const QString& saleGuid) const
{
    if (m_sales.isEmpty()) return false;

    QString latestGuid;
    QString latestDt;
    for (const SaleObject& s : m_sales) {
        if (s.dateTime() > latestDt) {
            latestDt   = s.dateTime();
            latestGuid = s.guid();
        }
    }
    return latestGuid == saleGuid;
}
