// MIT License
// Copyright (c) 2017 nessie1980 (nessie1980@gmx.de)
#include "PresenterSaleEdit.h"

#include <QProcess>
#include <QTimer>
#include <QUuid>
#include <QDateTime>
#include <QRegularExpression>

// ── Constructor ───────────────────────────────────────────────────────────────

PresenterSaleEdit::PresenterSaleEdit(IViewSaleEdit*   view,
                                     IModelSaleEdit*  model,
                                     const QString&   shareGuid,
                                     DocumentsConfig* config,
                                     QObject*         parent)
    : QObject(parent)
    , m_view(view)
    , m_model(model)
    , m_config(config)
    , m_shareGuid(shareGuid)
{
    connect(&m_parser, &ParserLib::Parser::parserUpdated,
            this,      &PresenterSaleEdit::onParserUpdated);

    // Populate available buys (no depot filter yet — depot not selected)
    m_view->populateAvailableBuys(m_model->loadAvailableBuys(shareGuid));
    // All buys (incl. fully sold) for document lookup in the Details dialog
    m_view->setAllBuys(m_model->loadAllBuys(shareGuid));

    reloadOverview();
    m_view->clearForm();
    m_view->setButtonStates(/*canRemove=*/false, /*isLastSale=*/false, /*isEdit=*/false);
}

// ── onSave ────────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onSave()
{
    const QString error = validateInput();
    if (!error.isEmpty()) {
        m_view->showError(error);
        return;
    }

    const bool isEdit = !m_currentSaleGuid.isEmpty();

    // Non-latest sale: only the document path may change
    if (isEdit && !m_isLastSale) {
        for (SaleObject& s : m_sales) {
            if (s.guid() == m_currentSaleGuid) {
                s.setDocument(m_view->documentPath().trimmed());
                if (!m_model->updateSale(s)) {
                    m_view->showError(m_model->lastError());
                    return;
                }
                emit dataChanged();
                reloadOverview();
                m_currentSaleGuid.clear();
                m_isLastSale = false;
                m_view->setButtonStates(false, false, false);
                m_view->showOverviewTab();
                return;
            }
        }
        return;
    }

    // New sale or latest-sale full edit
    const QString guid = isEdit
        ? m_currentSaleGuid
        : QUuid::createUuid().toString(QUuid::WithoutBraces);

    // Reconstruct SaleBuyDetails from existing sale (edit) or empty (new)
    // For new sales the buy details are built from the available buys displayed
    // in the Details dialog — for now we create a single auto-assigned detail
    // from the oldest available buy(s) in FIFO order.
    QList<SaleBuyDetail> buyDetails;
    if (isEdit) {
        // Preserve existing buy details (only document/brokerage changed)
        for (const SaleObject& s : std::as_const(m_sales)) {
            if (s.guid() == m_currentSaleGuid) {
                buyDetails = s.saleBuyDetails();
                break;
            }
        }
    } else {
        // Auto-assign FIFO: distribute sold volume across available buys
        // from the same depot, oldest first.
        double remaining = m_view->volume();
        const QList<BuyObject> available =
            m_model->loadAvailableBuysForDepot(m_shareGuid,
                                               m_view->depotNumber());
        for (const BuyObject& b : available) {
            if (remaining <= 1e-9) break;
            const double avail = b.volume() - b.volumeSold();
            if (avail <= 1e-9) continue;
            const double take = qMin(avail, remaining);
            buyDetails.append(SaleBuyDetail(
                b.guid(),
                b.dateTime(),
                take,
                b.price()));
            remaining -= take;
        }
    }

    const SaleObject sale(
        guid,
        m_shareGuid,
        m_view->depotNumber().trimmed(),
        m_view->orderNumber().trimmed(),
        m_view->dateTime(),
        m_view->volume(),
        m_view->salePrice(),
        buyDetails,
        m_view->taxAtSource(),
        m_view->capitalGainsTax(),
        m_view->solidarityTax(),
        QString(),   // brokerageGuid — generated by model
        m_view->provision(),
        m_view->brokerFee(),
        m_view->traderFee(),
        m_view->reduction(),
        m_view->documentPath().trimmed());

    const bool ok = isEdit
        ? m_model->updateSale(sale)
        : m_model->addSale(sale);

    if (!ok) { m_view->showError(m_model->lastError()); return; }

    emit dataChanged();
    reloadOverview();

    m_currentSaleGuid.clear();
    m_isLastSale = false;
    m_view->setButtonStates(false, false, false);
    m_view->showOverviewTab();
}

// ── onRemove ──────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onRemove()
{
    if (m_currentSaleGuid.isEmpty()) return;

    if (!m_isLastSale) {
        m_view->showError(tr("Dieser Verkauf kann nicht entfernt werden.\n"
                              "Es darf nur der jüngste Verkauf gelöscht werden."));
        return;
    }

    if (!m_model->removeSale(m_currentSaleGuid)) {
        m_view->showError(m_model->lastError());
        return;
    }

    emit dataChanged();
    m_currentSaleGuid.clear();
    m_isLastSale = false;
    reloadOverview();
    m_view->setButtonStates(false, false, false);
    m_view->showOverviewTab();
}

// ── onReset ───────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onReset()
{
    m_currentSaleGuid.clear();
    m_isLastSale = false;
    m_view->setButtonStates(false, false, false);
    // Clear depot filter — show all available buys again
    m_view->populateAvailableBuys(m_model->loadAvailableBuys(m_shareGuid));
    refreshDerivedValues();
    m_view->showOverviewTab();
}

// ── onClose ───────────────────────────────────────────────────────────────────

void PresenterSaleEdit::onClose()
{
    m_view->acceptAndClose();
}

// ── onRowSelected ─────────────────────────────────────────────────────────────

void PresenterSaleEdit::onRowSelected(const QString& saleGuid)
{
    if (saleGuid.isEmpty()) { onReset(); return; }

    for (const SaleObject& s : std::as_const(m_sales)) {
        if (s.guid() == saleGuid) {
            m_currentSaleGuid = saleGuid;
            m_isLastSale = isLatestSale(saleGuid);
            const bool canRemove = m_isLastSale;
            m_view->loadSale(s);
            // Refresh available buys for this sale's depot
            m_view->populateAvailableBuys(
                m_model->loadAvailableBuysForDepot(m_shareGuid,
                                                   s.depotNumber()));
            if (!s.document().isEmpty())
                m_view->openPdfPreview(s.document());
            else
                m_view->clearPdfPreview();
            m_view->setButtonStates(canRemove, m_isLastSale, /*isEdit=*/true);
            refreshDerivedValues();

            // Validate all fields so icons reflect the loaded state.
            onDateEdited();
            onDepotNumberEdited();
            onOrderNumberEdited();
            onVolumeOrPriceEdited();
            onFeeEdited(QStringLiteral("provision"),       m_view->provision());
            onFeeEdited(QStringLiteral("brokerFee"),       m_view->brokerFee());
            onFeeEdited(QStringLiteral("traderFee"),       m_view->traderFee());
            onFeeEdited(QStringLiteral("reduction"),       m_view->reduction());
            onTaxEdited(QStringLiteral("taxAtSource"),     m_view->taxAtSource());
            onTaxEdited(QStringLiteral("capitalGainsTax"), m_view->capitalGainsTax());
            onTaxEdited(QStringLiteral("solidarityTax"),   m_view->solidarityTax());
            onDocumentPathEdited();
            return;
        }
    }
}

// ── onValuesChanged ───────────────────────────────────────────────────────────

void PresenterSaleEdit::onValuesChanged()
{
    refreshDerivedValues();
}

// ── Live field validation ─────────────────────────────────────────────────────

void PresenterSaleEdit::onDateEdited()
{
    const QDate d = QDate::fromString(
        m_view->dateTime().left(10), Qt::ISODate);
    if (d.isValid() && d > QDate(2000, 1, 1))
        m_view->setFieldOk(QStringLiteral("date"), QString());
    else
        m_view->setFieldError(QStringLiteral("date"));
}

void PresenterSaleEdit::onDepotNumberEdited()
{
    if (!m_view->depotNumber().trimmed().isEmpty()) {
        m_view->setFieldOk(QStringLiteral("depotNumber"), QString());
    } else {
        m_view->setFieldError(QStringLiteral("depotNumber"));
    }
    // Refresh the buy list whenever the depot selection changes so the
    // Details dialog and FIFO calculation always use the right buys.
    m_view->populateAvailableBuys(
        m_model->loadAvailableBuysForDepot(m_shareGuid,
                                           m_view->depotNumber()));
    refreshDerivedValues();
}

void PresenterSaleEdit::onOrderNumberEdited()
{
    const QString nr = m_view->orderNumber().trimmed();
    if (nr.isEmpty()) {
        m_view->setFieldError(QStringLiteral("orderNumber"));
        return;
    }
    if (m_model->orderNumberExists(m_shareGuid, nr, m_currentSaleGuid))
        m_view->setFieldError(QStringLiteral("orderNumber"));
    else
        m_view->setFieldOk(QStringLiteral("orderNumber"), QString());
}

void PresenterSaleEdit::onVolumeOrPriceEdited()
{
    if (m_view->volume() > 0.0)
        m_view->setFieldOk(QStringLiteral("volume"), QString());
    else
        m_view->setFieldError(QStringLiteral("volume"));

    if (m_view->salePrice() > 0.0)
        m_view->setFieldOk(QStringLiteral("salePrice"), QString());
    else
        m_view->setFieldError(QStringLiteral("salePrice"));
}

void PresenterSaleEdit::onFeeEdited(const QString& fieldKey, double value)
{
    if (value < 0.0)
        m_view->setFieldError(fieldKey);
    else
        m_view->setFieldOk(fieldKey, QString());
}

void PresenterSaleEdit::onTaxEdited(const QString& fieldKey, double value)
{
    if (value < 0.0)
        m_view->setFieldError(fieldKey);
    else
        m_view->setFieldOk(fieldKey, QString());
}

void PresenterSaleEdit::onDocumentPathEdited()
{
    const QString path = m_view->documentPath().trimmed();
    if (path.isEmpty()) {
        m_view->setFieldOk(QStringLiteral("document"), QString());
        return;
    }
    if (m_model->documentExists(path, m_currentSaleGuid))
        m_view->setFieldError(QStringLiteral("document"));
    else
        m_view->setFieldOk(QStringLiteral("document"), QString());
}

// ── onDocumentSelected ────────────────────────────────────────────────────────

void PresenterSaleEdit::onDocumentSelected(const QString& path)
{
    if (path.isEmpty()) return;

    m_pendingPdfPath = path;
    m_view->openPdfPreview(path);

    // Non-latest sale: only document path changes, no re-parse
    const bool isNonLatestEdit = !m_currentSaleGuid.isEmpty() && !m_isLastSale;
    if (isNonLatestEdit) return;

    auto* proc = new QProcess(this);
    connect(proc,
            QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished),
            this,
            &PresenterSaleEdit::onPdfConversionFinished);

    const QStringList args = {
        QStringLiteral("-enc"),    QStringLiteral("UTF-8"),
        QStringLiteral("-layout"),
        path,
        QStringLiteral("-")
    };
    proc->start(QStringLiteral("pdftotext"), args);
}

// ── onPdfConversionFinished ───────────────────────────────────────────────────

void PresenterSaleEdit::onPdfConversionFinished(int exitCode, int /*exitStatus*/)
{
    auto* proc = qobject_cast<QProcess*>(sender());
    const QByteArray stdoutData = proc ? proc->readAllStandardOutput() : QByteArray();
    if (proc) proc->deleteLater();

    if (exitCode != 0 || stdoutData.isEmpty()) {
        m_view->showError(QObject::tr(
            "PDF-Konvertierung fehlgeschlagen oder kein Text extrahierbar."));
        return;
    }

    m_pdfText = QString::fromUtf8(stdoutData);
    startParserForText(m_pdfText);
}

// ── startParserForText ────────────────────────────────────────────────────────

void PresenterSaleEdit::startParserForText(const QString& pdfText)
{
    if (!m_config || !m_config->isValid()) return;

    const BankEntry* matchedBank = nullptr;
    for (const auto& bank : m_config->entries()) {
        const auto it = bank.identifierRegexList.constFind(
            QStringLiteral("BankIdentifier"));
        if (it == bank.identifierRegexList.constEnd()) continue;
        QRegularExpression re(it->regexExpression);
        if (re.isValid() && re.match(pdfText).hasMatch()) {
            matchedBank = &bank;
            break;
        }
    }

    if (!matchedBank) {
        const QStringList required = {
            "date","depotNumber","orderNumber","volume","salePrice"
        };
        for (const auto& f : required) m_view->setFieldError(f);
        m_view->onParseFinished();
        return;
    }

    DocumentType docType = DocumentType::Sale;
    const struct { const char* key; DocumentType type; } typeChecks[] = {
        { "BuyIdentifier",       DocumentType::Buy       },
        { "SaleIdentifier",      DocumentType::Sale      },
        { "DividendIdentifier",  DocumentType::Dividend  },
        { "BrokerageIdentifier", DocumentType::Brokerage }
    };
    for (const auto& check : typeChecks) {
        const auto it = matchedBank->identifierRegexList.constFind(
            QString::fromLatin1(check.key));
        if (it == matchedBank->identifierRegexList.constEnd()) continue;
        QRegularExpression re(it->regexExpression);
        if (re.isValid() && re.match(pdfText).hasMatch()) {
            docType = check.type;
            break;
        }
    }

    const DocumentEntry* docEntry =
        DocumentsConfig::findDocument(*matchedBank, docType);
    if (!docEntry) {
        m_view->onParseFinished();
        return;
    }

    m_view->setUiBusy(true);
    m_view->setParseProgress(0, QObject::tr("Dokumenten-Analyse läuft..."));

    ParserLib::ParsingValues pv(pdfText,
                                docEntry->encoding.isEmpty()
                                    ? QStringLiteral("UTF-8")
                                    : docEntry->encoding,
                                docEntry->regexList);
    m_parser.setParsingValues(pv);
    m_parser.startParsing();
}

// ── onParserUpdated ───────────────────────────────────────────────────────────

void PresenterSaleEdit::onParserUpdated(const ParserLib::ParserInfoState& state)
{
    if (state.lastErrorCode == ParserLib::ParserErrorCode::SearchRunning ||
        state.lastErrorCode == ParserLib::ParserErrorCode::SearchStarted)
    {
        const QString statusText = state.lastRegexListKey.isEmpty()
            ? QObject::tr("Dokumenten-Analyse läuft...")
            : QObject::tr("Analysiere: %1").arg(state.lastRegexListKey);
        m_view->setParseProgress(state.percentage, statusText);
        return;
    }

    if (state.lastErrorCode < ParserLib::ParserErrorCode::NoError &&
        state.lastErrorCode != ParserLib::ParserErrorCode::ParsingFailed)
    {
        m_view->setParseStatusIcon(1);
        m_view->setParseProgress(0, QObject::tr("Analyse fehlgeschlagen: %1")
                                    .arg(state.exceptionMessage));
        m_view->setUiBusy(false);
        m_view->showError(QObject::tr("Parser-Fehler: %1")
                          .arg(state.exceptionMessage));
        m_view->onParseFinished();
        return;
    }

    if (state.lastErrorCode == ParserLib::ParserErrorCode::Finished ||
        state.lastErrorCode == ParserLib::ParserErrorCode::ParsingFailed)
    {
        populateFromResult(state.searchResult);
    }
}

// ── populateFromResult ────────────────────────────────────────────────────────

void PresenterSaleEdit::populateFromResult(
    const QMap<QString, QList<QString>>& result)
{
    // ── WKN / ISIN-Prüfung ────────────────────────────────────────────────
    const ShareObject share = m_model->loadShare(m_shareGuid);
    if (share.isValid()) {
        const QString parsedWkn  = result.contains(QStringLiteral("Wkn"))
            ? result[QStringLiteral("Wkn")].value(0).trimmed().toUpper()
            : QString();
        const QString parsedIsin = result.contains(QStringLiteral("Isin"))
            ? result[QStringLiteral("Isin")].value(0).trimmed().toUpper()
            : QString();

        const bool wknMatch  = !parsedWkn.isEmpty()
            && parsedWkn.compare(share.wkn().trimmed(), Qt::CaseInsensitive) == 0;
        const bool isinMatch = !parsedIsin.isEmpty()
            && parsedIsin.compare(share.isin().trimmed(), Qt::CaseInsensitive) == 0;
        const bool anyParsed = !parsedWkn.isEmpty() || !parsedIsin.isEmpty();

        if (anyParsed && !wknMatch && !isinMatch) {
            QTimer::singleShot(0, this, [this, parsedWkn, parsedIsin,
                                          shareWkn = share.wkn()]() {
                m_view->setUiBusy(false);
                m_view->setParseStatusIcon(1);
                m_view->setParseProgress(100,
                    QObject::tr("Dokument gehört nicht zu dieser Aktie"));
                m_view->showError(
                    QObject::tr(
                        "Das gewählte Dokument gehört nicht zur aktuell geöffneten Aktie.\n\n"
                        "Dokument:  WKN %1 / ISIN %2\n"
                        "Aktie:     WKN %3")
                    .arg(parsedWkn.isEmpty() ? QObject::tr("(nicht gefunden)") : parsedWkn)
                    .arg(parsedIsin.isEmpty() ? QObject::tr("(nicht gefunden)") : parsedIsin)
                    .arg(shareWkn));
            });
            m_view->onParseFinished();
            return;
        }
    }

    static const QStringList knownXmlNames = {
        "Date","Time","DepotNumber","OrderNumber",
        "Volume","Price",
        "TaxAtSource","CapitalGainsTax","SolidarityTax",
        "Provision","BrokerFee","TraderPlaceFee","Reduction"
    };
    static const QStringList requiredXmlNames = {
        "Date","DepotNumber","OrderNumber","Volume","Price"
    };

    int found = 0, requiredFound = 0;
    for (const QString& xmlName : knownXmlNames) {
        const QString viewField = xmlNameToViewField(xmlName);
        if (viewField.isEmpty()) continue;

        if (result.contains(xmlName)) {
            const QList<QString>& values = result[xmlName];
            if (!values.isEmpty() && !values.first().trimmed().isEmpty()) {
                m_view->setFieldOk(viewField, values.first().trimmed());
                ++found;
                if (requiredXmlNames.contains(xmlName)) ++requiredFound;
            }
        }
    }

    m_view->onParseFinished();

    const int reqTotal      = requiredXmlNames.size();
    const int optionalFound = found - requiredFound;
    const int optionalTotal = knownXmlNames.size() - reqTotal;

    QTimer::singleShot(0, this, [this, requiredFound, reqTotal,
                                  optionalFound, optionalTotal]() {
        m_view->setUiBusy(false);

        if (requiredFound == reqTotal) {
            m_view->setParseStatusIcon(0);
            if (optionalFound > 0)
                m_view->setParseProgress(100,
                    QObject::tr("Analyse OK — %1/%1 Pflicht, %2/%3 Optional")
                    .arg(reqTotal).arg(optionalFound).arg(optionalTotal));
            else
                m_view->setParseProgress(100,
                    QObject::tr("Analyse OK — %1/%1 Pflicht").arg(reqTotal));
        } else {
            m_view->setParseStatusIcon(1);
            m_view->setParseProgress(100,
                QObject::tr("Analyse fehlgeschlagen — %1/%2 Pflicht")
                .arg(requiredFound).arg(reqTotal));
        }
    });
}

// ── xmlNameToViewField ────────────────────────────────────────────────────────

QString PresenterSaleEdit::xmlNameToViewField(const QString& xmlName)
{
    static const QMap<QString, QString> map = {
        { QStringLiteral("Date"),           QStringLiteral("date")           },
        { QStringLiteral("Time"),           QStringLiteral("time")           },
        { QStringLiteral("DepotNumber"),    QStringLiteral("depotNumber")    },
        { QStringLiteral("OrderNumber"),    QStringLiteral("orderNumber")    },
        { QStringLiteral("Volume"),         QStringLiteral("volume")         },
        { QStringLiteral("Price"),          QStringLiteral("salePrice")      },
        { QStringLiteral("TaxAtSource"),    QStringLiteral("taxAtSource")    },
        { QStringLiteral("CapitalGainsTax"),QStringLiteral("capitalGainsTax")},
        { QStringLiteral("SolidarityTax"),  QStringLiteral("solidarityTax")  },
        { QStringLiteral("Provision"),      QStringLiteral("provision")      },
        { QStringLiteral("BrokerFee"),      QStringLiteral("brokerFee")      },
        { QStringLiteral("TraderPlaceFee"), QStringLiteral("traderFee")      },
        { QStringLiteral("Reduction"),      QStringLiteral("reduction")      },
    };
    return map.value(xmlName, QString());
}

// ── reloadOverview ────────────────────────────────────────────────────────────

void PresenterSaleEdit::reloadOverview()
{
    m_sales = m_model->loadSales(m_shareGuid);
    m_view->populateOverview(m_sales);
}

// ── refreshDerivedValues ──────────────────────────────────────────────────────

void PresenterSaleEdit::refreshDerivedValues()
{
    const double vol        = m_view->volume();
    const double price      = m_view->salePrice();
    const double prov       = m_view->provision();
    const double broker     = m_view->brokerFee();
    const double trader     = m_view->traderFee();
    const double red        = m_view->reduction();
    const double taxSrc     = m_view->taxAtSource();
    const double taxCap     = m_view->capitalGainsTax();
    const double taxSol     = m_view->solidarityTax();

    const double saleValue    = vol * price;
    const double gesGebuehren = prov + broker + trader;
    const double taxSum       = taxSrc + taxCap + taxSol;
    const double auszahlung   = saleValue - gesGebuehren + red - taxSum;

    // Kaufwert und G/V berechnen
    double kaufwert  = 0.0;
    double gewinnVerlust = 0.0;
    {
        // Edit-Modus: gespeicherte Werte aus dem SaleObject verwenden
        if (!m_currentSaleGuid.isEmpty()) {
            for (const SaleObject& s : std::as_const(m_sales)) {
                if (s.guid() == m_currentSaleGuid) {
                    kaufwert     = s.buyValue();                      // Anzeige: ohne Kaufbrokerage
                    gewinnVerlust = s.profitLossBrokerageReduction(); // korrekte G/V inkl. aller Gebühren
                    break;
                }
            }
        } else {
            // New-Modus: FIFO-Vorschau aus depot-gefilterten Käufen
            double remaining = vol;
            const QList<BuyObject> available =
                m_model->loadAvailableBuysForDepot(m_shareGuid,
                                                   m_view->depotNumber());
            for (const BuyObject& b : available) {
                if (remaining <= 1e-9) break;
                const double avail = b.volume() - b.volumeSold();
                if (avail <= 1e-9) continue;
                const double take = qMin(avail, remaining);
                kaufwert  += take * b.price();
                remaining -= take;
            }
            // G/V-Vorschau: Verkaufsgebühren und Steuern abziehen
            // (Kaufbrokerage ist in der Vorschau nicht verfügbar)
            gewinnVerlust = saleValue - gesGebuehren + red - kaufwert - taxSum;
        }
    }

    m_view->setSaleValue(saleValue);
    m_view->setKaufwert(kaufwert);
    m_view->setGewinnVerlust(gewinnVerlust);
    m_view->setGesGebuehren(gesGebuehren);
    m_view->setTaxSum(taxSum);
    m_view->setAuszahlung(auszahlung);
}

// ── validateInput ─────────────────────────────────────────────────────────────

QString PresenterSaleEdit::validateInput() const
{
    QStringList missingFields;
    if (m_view->hasMissingRequiredFields(missingFields)) {
        m_view->markMissingFieldsAsFailed();
        return QObject::tr(
            "Es fehlen noch Pflichtangaben.\n"
            "Die fehlenden Felder sind in der Maske rot markiert.");
    }

    if (m_model->orderNumberExists(m_shareGuid,
                                   m_view->orderNumber().trimmed(),
                                   m_currentSaleGuid)) {
        return QObject::tr("Die Auftragsnummer \"%1\" ist für diese Aktie bereits vorhanden.")
               .arg(m_view->orderNumber().trimmed());
    }

    const QString doc = m_view->documentPath().trimmed();
    if (!doc.isEmpty() && m_model->documentExists(doc, m_currentSaleGuid)) {
        return QObject::tr("Das Dokument \"%1\" ist bereits einem anderen Verkauf zugeordnet.")
               .arg(doc);
    }

    return QString();
}

// ── isLatestSale ──────────────────────────────────────────────────────────────

bool PresenterSaleEdit::isLatestSale(const QString& saleGuid) const
{
    if (m_sales.isEmpty()) return false;

    QString latestGuid;
    QString latestDt;
    for (const SaleObject& s : m_sales) {
        if (s.dateTime() > latestDt) {
            latestDt   = s.dateTime();
            latestGuid = s.guid();
        }
    }
    return latestGuid == saleGuid;
}
